spring:
  datasource:
    url: jdbc:log4jdbc:mysql://121.65.128.115:33306/nwTr # jdbc:mysql://192.168.0.99:3306/nwTr #
    username: trs
    password: Vtw2023!
    driver-class-name:  net.sf.log4jdbc.sql.jdbcapi.DriverSpy #com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2GB  # 최대 파일 크기
      max-request-size: 2GB
  mail:
    host: smtp.office365.com
    port: 587
    username: admin@vtw.co.kr
    password: "!!!vkvk5600"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  mapper-locations: /mybatis/mapper/**/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
server:
  port: 8090
  address: 0.0.0.0
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO  #SQL 결과 데이터 Table형식으로 출력
      sqlonly: INFO
      sqltiming: WARN
      connection : OFF
      log4jdbc.log4j2: ERROR
jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: eyJhbGciOiJIUzUxMiJ9eyJzdWIiOiJ1c2VyIn0I2qOfhAZMGSH1pCecUH5sV2Lg2pSWNQMPzXsMcne6NJ1SlkBoirhGAmKfTYNcRyhu6nQtRzgAd6VXyttoX9A
  tokenExpirationTime: 3600
