spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  datasource:
    url: jdbc:log4jdbc:mysql://121.65.128.115:33306/nwTr # jdbc:mysql://192.168.0.99:3306/nwTr #
    username: trs
    password: Vtw2023!
    driver-class-name:  net.sf.log4jdbc.sql.jdbcapi.DriverSpy #com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: /mybatis/mapper/**/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
server:
  port: 8080
  address: 0.0.0.0
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO  #SQL 결과 데이터 Table형식으로 출력
      sqlonly: INFO
      sqltiming: WARN
      connection : OFF
      log4jdbc.log4j2: ERROR



